name: dbtvault_databricks
profile: dbtvault_databricks
config-version: 2

analysis-paths:
  - analysis
clean-targets:
  - target
macro-paths:
  - macros
model-paths:
  - models
test-paths:
  - tests
target-path: target

vars:
  load_date: "2024-04-22"

models:
  dbtvault_databricks:
    enriched:
      +materialized: incremental
      +tags:
        - 'enriched'

    stage:
      +materialized: view
      +tags:
        - 'stage'
      +enabled: true

    curated:
      +materialized: incremental
      +tags:
        - 'raw_vault'
      hubs:
        +tags:
          - 'hub'
      links:
        +tags:
          - 'link'
      sats:
        +tags:
          - 'satellite'
      t_links:
        +tags:
          - 't_link'
