dbtvault_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: dbtvault_databricks
      schema: lakehouse
      host: adb-2777141288726595.15.azuredatabricks.net
      http_path: sql/protocolv1/o/2777141288726595/0418-083919-hj4ytgn1
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"