
version: 2

models:
  - name: orders_raw
    description: "Raw ingested orders"
    columns:
      - name: customer_name
        description: "The name of a customer"
        tests:
          - unique
          - not_null

  - name: orders_daily
    description: "Number of orders by day"
    columns:
      - name: order_date
        description: "The date on which orders took place"
        tests:
          - unique
          - not_null
