version: 2

sources:
  - name: tpch_sample
    schema: raw
    tables:
      - name: lineitems
      - name: cutomers
      - name: orders
      - name: partsupp
      - name: supplier
      - name: part
      - name: nations
      - name: region